<?php


namespace Modules\Themes\BounceBackHub\Providers;


use Illuminate\Support\ServiceProvider;

class BounceBackHubProvider extends ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {

    }

}
