<?php


namespace Modules\Themes\Portfolio\Providers;


use Illuminate\Support\ServiceProvider;

class PortfolioProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        // boot things up
    }
}
